import React from 'react';
export const adminDetails = () => <div>admin distinct</div>;
export const admin_detail_0 = (p:any)=> <div>admin 0 venue mgmt</div>;
export const admin_detail_1 = (p:any)=> <div>admin 1 event creation</div>;
export const admin_detail_2 = (p:any)=> <div>admin 2 staff</div>;
export const admin_detail_3 = (p:any)=> <div>admin 3 venue mgmt</div>;
export const admin_detail_4 = (p:any)=> <div>admin 4 event creation</div>;
export const admin_detail_5 = (p:any)=> <div>admin 5 staff</div>;
export const admin_detail_6 = (p:any)=> <div>admin 6 venue mgmt</div>;
export const admin_detail_7 = (p:any)=> <div>admin 7 event creation</div>;
export const admin_detail_8 = (p:any)=> <div>admin 8 staff</div>;
export const admin_detail_9 = (p:any)=> <div>admin 9 venue mgmt</div>;
export const admin_detail_10 = (p:any)=> <div>admin 10 event creation</div>;
export const admin_detail_11 = (p:any)=> <div>admin 11 staff</div>;
export const admin_detail_12 = (p:any)=> <div>admin 12 venue mgmt</div>;
export const admin_detail_13 = (p:any)=> <div>admin 13 event creation</div>;
export const admin_detail_14 = (p:any)=> <div>admin 14 staff</div>;
export const admin_detail_15 = (p:any)=> <div>admin 15 venue mgmt</div>;
export const admin_detail_16 = (p:any)=> <div>admin 16 event creation</div>;
export const admin_detail_17 = (p:any)=> <div>admin 17 staff</div>;
export const admin_detail_18 = (p:any)=> <div>admin 18 venue mgmt</div>;
export const admin_detail_19 = (p:any)=> <div>admin 19 event creation</div>;