import React from 'react';
export const concurrencyDetails = () => <div>concurrency distinct</div>;
export const concurrency_detail_0 = (p:any)=> <div>concurrency 0 seat-lock</div>;
export const concurrency_detail_1 = (p:any)=> <div>concurrency 1 distributed lock</div>;
export const concurrency_detail_2 = (p:any)=> <div>concurrency 2 waiting room</div>;
export const concurrency_detail_3 = (p:any)=> <div>concurrency 3 high load</div>;
export const concurrency_detail_4 = (p:any)=> <div>concurrency 4 seat-lock</div>;
export const concurrency_detail_5 = (p:any)=> <div>concurrency 5 distributed lock</div>;
export const concurrency_detail_6 = (p:any)=> <div>concurrency 6 waiting room</div>;
export const concurrency_detail_7 = (p:any)=> <div>concurrency 7 high load</div>;
export const concurrency_detail_8 = (p:any)=> <div>concurrency 8 seat-lock</div>;
export const concurrency_detail_9 = (p:any)=> <div>concurrency 9 distributed lock</div>;
export const concurrency_detail_10 = (p:any)=> <div>concurrency 10 waiting room</div>;
export const concurrency_detail_11 = (p:any)=> <div>concurrency 11 high load</div>;
export const concurrency_detail_12 = (p:any)=> <div>concurrency 12 seat-lock</div>;
export const concurrency_detail_13 = (p:any)=> <div>concurrency 13 distributed lock</div>;
export const concurrency_detail_14 = (p:any)=> <div>concurrency 14 waiting room</div>;
export const concurrency_detail_15 = (p:any)=> <div>concurrency 15 high load</div>;
export const concurrency_detail_16 = (p:any)=> <div>concurrency 16 seat-lock</div>;
export const concurrency_detail_17 = (p:any)=> <div>concurrency 17 distributed lock</div>;
export const concurrency_detail_18 = (p:any)=> <div>concurrency 18 waiting room</div>;
export const concurrency_detail_19 = (p:any)=> <div>concurrency 19 high load</div>;