import React from 'react';
export const seatingDetails = () => <div>seating distinct</div>;
export const seating_detail_0 = (p:any)=> <div>seating 0 seat map</div>;
export const seating_detail_1 = (p:any)=> <div>seating 1 dynamic pricing</div>;
export const seating_detail_2 = (p:any)=> <div>seating 2 holds</div>;
export const seating_detail_3 = (p:any)=> <div>seating 3 locks</div>;
export const seating_detail_4 = (p:any)=> <div>seating 4 seat map</div>;
export const seating_detail_5 = (p:any)=> <div>seating 5 dynamic pricing</div>;
export const seating_detail_6 = (p:any)=> <div>seating 6 holds</div>;
export const seating_detail_7 = (p:any)=> <div>seating 7 locks</div>;
export const seating_detail_8 = (p:any)=> <div>seating 8 seat map</div>;
export const seating_detail_9 = (p:any)=> <div>seating 9 dynamic pricing</div>;
export const seating_detail_10 = (p:any)=> <div>seating 10 holds</div>;
export const seating_detail_11 = (p:any)=> <div>seating 11 locks</div>;
export const seating_detail_12 = (p:any)=> <div>seating 12 seat map</div>;
export const seating_detail_13 = (p:any)=> <div>seating 13 dynamic pricing</div>;
export const seating_detail_14 = (p:any)=> <div>seating 14 holds</div>;
export const seating_detail_15 = (p:any)=> <div>seating 15 locks</div>;
export const seating_detail_16 = (p:any)=> <div>seating 16 seat map</div>;
export const seating_detail_17 = (p:any)=> <div>seating 17 dynamic pricing</div>;
export const seating_detail_18 = (p:any)=> <div>seating 18 holds</div>;
export const seating_detail_19 = (p:any)=> <div>seating 19 locks</div>;